print("Hello from lesson 2")
print("Hello World")
print("Skibidi")
print("Skibidi")
print("Skibidi")
print("Skibidi")
print("Skibidi")
print("Skibidi")
print("Skibidi")
print("Skibidi")
print("Skibidi")
print("Skibidi")
print("Skibidi")
